name: Feature Request
description: Suggest a new feature for @kopexa/krn
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

        **Important:** The Go package ([kopexa-grc/krn](https://github.com/kopexa-grc/krn)) is the source of truth.
        New features should typically be implemented in Go first, then ported to TypeScript.

        If this feature affects both packages, please also open an issue in the Go repo.

  - type: checkboxes
    id: go-compatibility
    attributes:
      label: Go Compatibility
      description: Have you considered the Go package?
      options:
        - label: This feature already exists in the Go package
        - label: I will also open an issue in the Go repo
        - label: This is TypeScript-specific (e.g., type definitions)

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or screenshots.
